version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Budapest
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /apps/manager
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Budapest
    labels:
      - dependencies
    groups:
      manager-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /services/managerd
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Budapest
    labels:
      - dependencies
    groups:
      go-dependencies:
        patterns:
          - "*"
