package webui

import (
	"embed"
	"io/fs"
)

// files contains the device-hosted manager generated by `npm run build:device`
// in apps/manager.
//
//go:embed dist
var files embed.FS

func Files() fs.FS {
	dist, err := fs.Sub(files, "dist")
	if err != nil {
		panic(err)
	}
	return dist
}
