#pragma once

// Lamp Black type scale (mockups/lvgl-taste/1-lamp-black.html). Generated by
// scripts/generate-lamp-black-fonts.sh; names are family, CSS weight and pixel size.
#include <lvgl.h>

extern const lv_font_t ardor_lb_cond500_12;
extern const lv_font_t ardor_lb_cond500_22;
extern const lv_font_t ardor_lb_cond600_12;
extern const lv_font_t ardor_lb_cond600_14;
extern const lv_font_t ardor_lb_cond600_15;
extern const lv_font_t ardor_lb_cond600_16;
extern const lv_font_t ardor_lb_cond600_18;
extern const lv_font_t ardor_lb_cond600_19;
extern const lv_font_t ardor_lb_cond600_20;
extern const lv_font_t ardor_lb_cond600_22;
extern const lv_font_t ardor_lb_cond600_30;
extern const lv_font_t ardor_lb_cond700_13;
extern const lv_font_t ardor_lb_cond700_14;
extern const lv_font_t ardor_lb_cond700_15;
extern const lv_font_t ardor_lb_cond700_16;
extern const lv_font_t ardor_lb_cond700_17;
extern const lv_font_t ardor_lb_cond700_18;
extern const lv_font_t ardor_lb_cond700_20;
extern const lv_font_t ardor_lb_cond700_22;
extern const lv_font_t ardor_lb_cond700_24;
extern const lv_font_t ardor_lb_cond700_28;
extern const lv_font_t ardor_lb_cond700_30;
extern const lv_font_t ardor_lb_cond700_44;
extern const lv_font_t ardor_lb_cond700_50;
extern const lv_font_t ardor_lb_cond700_52;
extern const lv_font_t ardor_lb_cond700_76;
extern const lv_font_t ardor_lb_cond800_13;
extern const lv_font_t ardor_lb_cond800_32;
extern const lv_font_t ardor_lb_cond800_40;
extern const lv_font_t ardor_lb_cond800_96;
extern const lv_font_t ardor_lb_mono500_13;
extern const lv_font_t ardor_lb_saira400_15;
extern const lv_font_t ardor_lb_saira500_15;
extern const lv_font_t ardor_lb_saira500_18;
extern const lv_font_t ardor_lb_saira600_15;
extern const lv_font_t ardor_lb_saira600_22;
extern const lv_font_t ardor_lb_saira600_26;
extern const lv_font_t ardor_lb_saira700_26;
