// Emits the device's own rendering of every Daisy effect parameter as JSON.
//
// apps/manager/src/effects/daisyValues.ts is a hand-written TypeScript mirror of
// formatMod/formatDelay/formatReverb in DaisyFxCatalog.cpp. Nothing kept the two
// in step, and they had already drifted: the Whammy was missing entirely and the
// Quadrature sub-mode list still said "FM" after the C++ was renamed. This tool
// writes the C++ side out as a fixture so a manager test can assert parity.
//
// Regenerate with:
//   cmake --build <build> --target daisy-values-dump
//   ./<build>/daisy-values-dump > apps/manager/src/effects/daisyValues.fixture.json

#include "daisyfx/DaisyFxCatalog.h"

#include <cstdio>
#include <string>
#include <vector>

namespace {

std::string escape(const std::string& value)
{
  std::string out;
  out.reserve(value.size() + 8);
  for (const char c : value) {
    switch (c) {
      case '"':  out += "\\\""; break;
      case '\\': out += "\\\\"; break;
      case '\n': out += "\\n";  break;
      default:   out += c;      break;
    }
  }
  return out;
}

} // namespace

int main()
{
  std::printf("{\n");
  std::printf("  \"comment\": \"Generated by apps/daisy-values-dump. Do not edit by hand.\",\n");
  std::printf("  \"effects\": [\n");

  const auto& catalog = ardor::daisyFxCatalog();
  bool firstEffect = true;
  for (const auto& effect : catalog) {
    if (!firstEffect) std::printf(",\n");
    firstEffect = false;
    std::printf("    {\n");
    std::printf("      \"id\": \"%s:%s\",\n", effect.blockType.c_str(), effect.mode.c_str());
    std::printf("      \"blockType\": \"%s\",\n", effect.blockType.c_str());
    std::printf("      \"mode\": \"%s\",\n", effect.mode.c_str());
    std::printf("      \"params\": [\n");

    bool firstParam = true;
    for (const auto& param : effect.params) {
      if (!firstParam) std::printf(",\n");
      firstParam = false;
      const auto spec = ardor::daisyFxParamControlSpec(effect, param);

      // Sample the whole range for continuous controls; for discrete ones use
      // the exact values the device offers, so a count mismatch shows up.
      //
      // The interior points deliberately avoid tidy fractions. C's printf
      // rounds halves to even and JavaScript's toFixed rounds them away from
      // zero, so a sample landing exactly on x.5 makes the two disagree by one
      // digit for reasons that have nothing to do with the formatter being
      // wrong. This test is for semantic drift — wrong names, wrong formulas,
      // missing modes — not for tie-breaking parity between two languages.
      std::vector<float> samples;
      if (spec.choiceValues.empty()) {
        samples = {0.0f, 0.23f, 0.47f, 0.71f, 1.0f};
      } else {
        samples = spec.choiceValues;
      }

      std::printf("        {\n");
      std::printf("          \"key\": \"%s\",\n", param.key.c_str());
      std::printf("          \"label\": \"%s\",\n", escape(param.label).c_str());
      std::printf("          \"defaultValue\": %.6f,\n", param.defaultValue);
      std::printf("          \"choiceCount\": %zu,\n", spec.choiceValues.size());
      std::printf("          \"samples\": [");
      for (std::size_t i = 0; i < samples.size(); ++i) {
        if (i != 0) std::printf(", ");
        std::printf("{\"value\": %.6f, \"text\": \"%s\"}", samples[i],
                    escape(ardor::formatDaisyFxParamValue(effect, param, samples[i])).c_str());
      }
      std::printf("]\n");
      std::printf("        }");
    }
    std::printf("\n      ]\n");
    std::printf("    }");
  }

  std::printf("\n  ]\n}\n");
  return 0;
}
