FROM ubuntu:24.04

ARG APT_MIRROR=http://archive.ubuntu.com/ubuntu

RUN set -eux; \
    sed -i "s|http://archive.ubuntu.com/ubuntu/|${APT_MIRROR%/}/|g" /etc/apt/sources.list.d/ubuntu.sources; \
    export DEBIAN_FRONTEND=noninteractive; \
    apt-get -o Acquire::Retries=3 update; \
    apt-get install -y --no-install-recommends \
      build-essential git curl wget rsync cpio unzip bc \
      python3 python3-dev file pkg-config libssl-dev libelf-dev \
      dosfstools genimage e2fsprogs mtools device-tree-compiler openssh-client; \
    rm -rf /var/lib/apt/lists/*
