#!/usr/bin/env bash
# Regenerates the Lamp Black LVGL fonts in src/ui/fonts/lamp/.
#
# Sources (all SIL OFL 1.1):
#   Saira Condensed  https://github.com/google/fonts/tree/main/ofl/sairacondensed
#   Saira            https://github.com/google/fonts/tree/main/ofl/saira (variable;
#                    static weights are cut with fontTools.varLib.instancer)
#   JetBrains Mono   https://github.com/JetBrains/JetBrainsMono
#
# Usage: scripts/generate-lamp-black-fonts.sh <directory-with-ttf-files>
# The directory must hold SairaCondensed-{Medium,SemiBold,Bold,ExtraBold}.ttf,
# Saira-{400,500,600,700}.ttf and JetBrainsMono-Medium.ttf.
set -euo pipefail

ttf="${1:?usage: $0 <ttf-directory>}"
root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/src/ui/fonts/lamp"
range="0x20-0x7E,0xB0,0xB1,0xB7,0xD7,0x2013,0x2014,0x2026,0x2212"
mkdir -p "$out"

generate() {
  local file="$1" size="$2" name="$3"
  npx -y lv_font_conv --font "$ttf/$file" --size "$size" --bpp 4 --format lvgl \
    --lv-include lvgl.h --lv-font-name "$name" -r "$range" -o "$out/$name.c"
}

for size in 12 22; do generate SairaCondensed-Medium.ttf "$size" "ardor_lb_cond500_$size"; done
for size in 12 14 15 16 18 19 20 22 30; do
  generate SairaCondensed-SemiBold.ttf "$size" "ardor_lb_cond600_$size"
done
for size in 13 14 15 16 17 18 20 22 24 28 30 44 50 52 76; do
  generate SairaCondensed-Bold.ttf "$size" "ardor_lb_cond700_$size"
done
for size in 13 32 40 96; do generate SairaCondensed-ExtraBold.ttf "$size" "ardor_lb_cond800_$size"; done
generate Saira-400.ttf 15 ardor_lb_saira400_15
for size in 15 18; do generate Saira-500.ttf "$size" "ardor_lb_saira500_$size"; done
for size in 15 22 26; do generate Saira-600.ttf "$size" "ardor_lb_saira600_$size"; done
generate Saira-700.ttf 26 ardor_lb_saira700_26
generate JetBrainsMono-Medium.ttf 13 ardor_lb_mono500_13

{
  echo '#pragma once'
  echo
  echo '// Lamp Black type scale (mockups/lvgl-taste/1-lamp-black.html). Generated by'
  echo '// scripts/generate-lamp-black-fonts.sh; names are family, CSS weight and pixel size.'
  echo '#include <lvgl.h>'
  echo
  for file in "$out"/*.c; do echo "extern const lv_font_t $(basename "$file" .c);"; done
} > "$root/src/ui/fonts/LampBlackFonts.h"
